package:
  name: giropops-senhas
  version: 0.1
  epoch: 0
  description: Password Generator by LinuxTips
  target-architecture:
    - x86_64
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - ./melange.rsa.pub
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - gcc
      - musl-dev
      - python3
      - python3-dev
      - py3-pip
      - py3-virtualenv

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/badtuxx/giropops-senhas/archive/refs/heads/main.tar.gz
      expected-sha256: 5743d189589bbcbed3f5f1872feb694d77027599c3c2d7b8514dc0122b043d46
      strip-components: 1

  - name: Build Python application
    runs: |
      set -ex
      EXECDIR="${{targets.destdir}}/usr/bin"
      APPDIR="${{targets.destdir}}/usr/share/giropops-senhas"
      mkdir -p "$EXECDIR" "$APPDIR"

      echo "#!/usr/share/giropops-senhas/venv/bin/python3" > "$EXECDIR/giropops-senhas"
      cat app.py >> "$EXECDIR/giropops-senhas"
      chmod +x "$EXECDIR/giropops-senhas"

      virtualenv "$APPDIR/venv"
      cp -r templates static requirements.txt "$APPDIR/"
      source "$APPDIR/venv/bin/activate"
      pip install -r "$APPDIR/requirements.txt"

update:
  enabled: false