apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.redis.name }}
  labels:
    app: {{ .Values.deployments.redis.labels.app }}
spec:
  replicas: {{ .Values.deployments.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployments.redis.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.redis.labels.app }}
    spec:
      containers:
      - name: redis
        image: {{ .Values.deployments.redis.image }}
        ports:
          - containerPort: 6379
        resources:
          requests:
            memory: {{ .Values.deployments.redis.resources.requests.memory }}
            cpu: {{ .Values.deployments.redis.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployments.redis.resources.limits.memory }}
            cpu: {{ .Values.deployments.redis.resources.limits.cpu }}
        command: ["redis-server", "--appendonly", "yes"]  # Permite persistência dos dados