apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: {{ .Values.services.redis.labels.app }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.services.redis.labels.app }}
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379