deployments:
  giropops-senhas:
    name: "giropops-senhas"
    image: "geforce8400gsd/giropops-senhas:latest"
    replicas: 1
    ports:
      - port: 5000
        targetPort: 5000
        name: "giropops-senhas-port"
        serviceType: "NodePort"
        NodePort: 32500
      - port: 8088
        targetPort: 8088
        name: "giropops-senhas-metrics"
        serviceType: "ClusterIP"
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "true"
    resources:
      requests:
        memory: "32Mi"
        cpu: "250m"
      limits:
        memory: "64Mi"
        cpu: "500m"

  redis:
    name: "redis"
    image: "redis"
    replicas: 1
    labels:
      app: "redis"
      env: "labs"
      live: "true"
    resources:
      requests:
        memory: "32Mi"
        cpu: "250m"
      limits:
        memory: "64Mi"
        cpu: "500m"

services:
  giropops-senhas:
    ports:
      - port: 5000
        targetPort: 5000
        name: "giropops-senhas-port"
        serviceType: "ClusterIP"
        NodePort: 32500
      - port: 8088
        targetPort: 8088
        name: "giropops-senhas-metrics"
        serviceType: "ClusterIP"
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "true"

  redis:
    ports:
      - port: 6379
        targetPort: 6379
        name: "redis-port"
        serviceType: "ClusterIP" 
    labels:
      app: "redis"
      env: "labs"
      live: "true"

configMap:
  name: "locust-config"
  namespace: "dev"
  data:
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"


hpa:
  enabled: false  # Define se o HPA será criado
  minReplicas: 1
  maxReplicas: 1
  cpuUtilization: 50  # Escala se a CPU ultrapassar 50%
  memoryUtilization: 70  # Escala se a Memória ultrapassar 70%

locust:
  enabled: false  # Habilita ou desabilita o Locust
  image: "geforce8400gsd/giropops-senhas:latest"
  replicas: 1
  service:
    type: NodePort  # Pode ser LoadBalancer na nuvem
    port: 8089
  scriptConfigMap: "locust-scripts"  # Nome do ConfigMap com o locustfile.py


ingress:
  enabled: true
  host: dev.giropops.local
  serviceName: giropops-senhas-giropops-senhas-port
  servicePort: 5000
  allowIpAccess: true


