apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-falha
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliance
  template:
    metadata:
      labels:
        app: compliance
    spec:
      containers:
        - name: app
          image: busybox
          command: ["sleep", "3600"]
