apiVersion: v1
kind: Pod
metadata:
  name: pod-env-sensivel
  namespace: prod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sleep", "3600"]
      env:
        - name: PASSWORD
          value: "1234"
