apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: giropops-cert
  namespace: prod
spec:
  secretName: giropops-tls
  dnsNames:
    - prod.giropops.local
  issuerRef:
    name: giropops-ca-issuer
    kind: Issuer
