apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: giropops-local-tls
  namespace: default
spec:
  secretName: giropops-local-tls
  issuerRef:
    name: giropops-ca
    kind: Issuer
  commonName: giropops.local
  dnsNames:
    - giropops.local