name: CI/CD - Deploy Kubernetes (Dev, Staging, Prod)

on:
  push:
    branches:
      - main
      - dev
      - staging
    paths:
      - '**.yaml'  # Só roda se mudar YAMLs
  workflow_dispatch:  # Manual para produção

jobs:
  deploy:
    name: Deploy Kubernetes via Helm
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cluster Info
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy para DEV
        if: github.ref == 'refs/heads/dev'
        run: |
          helm upgrade --install meu-app-dev ${{ github.workspace }} \
          --namespace dev \
          -f ${{ github.workspace }}/values-dev.yaml

      - name: Deploy para STAGING
        if: github.ref == 'refs/heads/staging'
        run: |
          helm upgrade --install meu-app-staging ${{ github.workspace }} \
          --namespace staging \
          -f ${{ github.workspace }}/values-staging.yaml

      - name: Deploy para PROD
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: |
          helm upgrade --install meu-app-prod ${{ github.workspace }} \
          --namespace prod \
          -f ${{ github.workspace }}/values-prod.yaml
