name: CI/CD - Helm Upgrade Kubernetes (Dev, Staging, Prod)

on:
  push:
    branches:
      - main
      - develop
      - staging
    paths:
      - '**/*.yaml'
  workflow_dispatch:

jobs:
  deploy:
    name: Helm Upgrade - Kubernetes
    runs-on: self-hosted

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar kubectl
        run: |
          export KUBECONFIG=/home/github-runner/.kube/config
          kubectl cluster-info
          kubectl get nodes

      - name: Verificar Estrutura do Projeto
        run: |
          pwd
          ls -laR

      - name: Verificar assinatura da imagem
        run: |
          echo "${{ secrets.COSIGN_PUB }}" > cosign.pub
          cosign verify --key cosign.pub docker.io/geforce8400gsd/giropops-senhas:1.0 || echo " Imagem ainda não assinada."

      - name: Assinar imagem com Cosign (se necessário)
        run: |
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key
          echo "${{ secrets.COSIGN_PASSWORD }}" > cosign.pass
          export COSIGN_PASSWORD=$(cat cosign.pass)
          cosign sign --key cosign.key --yes docker.io/geforce8400gsd/giropops-senhas:1.0
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Deploy para DEV
        if: github.ref == 'refs/heads/develop'
        run: |
          helm upgrade --install giropops-dev ${{ github.workspace }}/Helm \
            --namespace dev \
            -f ${{ github.workspace }}/Helm/values-dev.yaml \
            --set deployments.giropops-senhas.image=geforce8400gsd/giropops-senhas:1.0

      - name: Deploy para STAGING
        if: github.ref == 'refs/heads/staging'
        run: |
          helm upgrade --install giropops-staging ${{ github.workspace }}/Helm \
            --namespace staging \
            -f ${{ github.workspace }}/Helm/values-staging.yaml \
            --set deployments.giropops-senhas.image=geforce8400gsd/giropops-senhas:1.0

      - name: Deploy para PRODUÇÃO (manual)
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: |
          helm upgrade --install giropops-prod ${{ github.workspace }}/Helm \
            --namespace prod \
            -f ${{ github.workspace }}/Helm/values-prod.yaml \
            --set deployments.giropops-senhas.image=geforce8400gsd/giropops-senhas:1.0
