name: CI/CD - Deploy Kubernetes (Dev, Staging, Prod)

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**.yaml'  # Só executa se houver mudanças nos arquivos .yaml (ex: manifests Helm)
  workflow_dispatch:  # Permite execução manual (ex: produção)

jobs:
  deploy:
    name: Deploy para Kubernetes
    runs-on: self-hosted  # Runner instalado em uma VM com acesso ao cluster

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar kubectl
        run: |
          export KUBECONFIG=/home/github-runner/.kube/config
          kubectl cluster-info
          kubectl get nodes

      - name: Verificar diretório atual
        run: |
          pwd
          ls -R  # Verifica se os arquivos e os charts estão no caminho certo

      - name: Verificar conteúdo do values-staging.yaml
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "📄 Conteúdo do values-staging.yaml:"
          cat /opt/actions-runner/_work/PICK-2024-Teste/PICK-2024-Teste/values-staging.yaml


      - name: Deploy para DEV
        if: github.ref == 'refs/heads/develop'
        run: |
          helm upgrade --install giropops-dev /opt/actions-runner/_work/PICK-2024-Teste/PICK-2024-Teste \
          --namespace dev \
          -f /opt/actions-runner/_work/PICK-2024-Teste/PICK-2024-Teste/values-dev.yaml \
          --set deployments.giropops-senhas.image=linuxtips/giropops-senhas:1.0

      - name: Deploy para STAGING
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          helm upgrade --install giropops-staging /opt/actions-runner/_work/PICK-2024-Teste/PICK-2024-Teste \
          --namespace staging \
          -f /opt/actions-runner/_work/PICK-2024-Teste/PICK-2024-Teste/values-staging.yaml \
          --set deployments.giropops-senhas.image=linuxtips/giropops-senhas:1.0

      - name: Deploy para PRODUÇÃO (manual)
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: |
          helm upgrade --install giropops-prod /opt/actions-runner/_work/PICK-2024-Teste/PICK-2024-Teste \
          --namespace prod \
          -f /opt/actions-runner/_work/PICK-2024-Teste/PICK-2024-Teste/values-prod.yaml \
          --set deployments.giropops-senhas.image=linuxtips/giropops-senhas:1.0
